- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/registration/Registration.Service.Tests/Controller/RegistrationControllerTest.cs
- tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
fixes finding https://github.com/catenax-ng/product-portal-backend/pull/367#discussion_r1041924304
> CPLP-1828 fix query validating calling users association with application

- .github/workflows/veracode.yaml
There is currently an issue with with the module selection in veracode workflow and I just decided to limit it to main module in order to make the connection to veracode less error prone.
https://jira.catena-x.net/browse/CPLP-1576
> CPLP-1576: Change module selection for veracode workflow

- src/administration/Administration.Service/BusinessLogic/BpdmService.cs
- src/administration/Administration.Service/BusinessLogic/BpdmServiceSettings.cs
- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/DapsService.cs
- src/administration/Administration.Service/BusinessLogic/DapsServiceCollectionExtension.cs
- src/administration/Administration.Service/BusinessLogic/DapsSettings.cs
- src/administration/Administration.Service/BusinessLogic/IDapsService.cs
- src/administration/Administration.Service/BusinessLogic/KeyVaultAuthSettings.cs
- src/administration/Administration.Service/appsettings.json
- src/marketplace/Apps.Service/Program.cs
- src/marketplace/Apps.Service/Properties/launchSettings.json
- src/marketplace/Apps.Service/appsettings.json
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/DapsServiceTests.cs
In this PR [CPLP-1860](https://jira.catena-x.net/browse/CPLP-1860) is resolved.
> CPLP-1860 daps

- src/Portal.Backend.sln
- src/maintenance/Maintenance.App/BatchDeleteService.cs
- tests/maintenance/Maintenance.App.Tests/BatchDeleteServiceTests.cs
- tests/maintenance/Maintenance.App.Tests/Maintenance.App.Tests.csproj
- tests/maintenance/Maintenance.App.Tests/Setup/TestDbFixture.cs
- tests/maintenance/Maintenance.App.Tests/Usings.cs
- tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
In this PR [CPLP-1918](https://jira.catena-x.net/browse/CPLP-1918) is fixed
> CPLP-1918 edit batch delete job

- postman/CatenaX Portal Service-local.postman_collection.json
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
- src/marketplace/Offers.Library/Models/OfferingData.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryFakeDbTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
added  LocalizedDescription to ServiceCreation
> CPLP-1840 post service

- src/portalbackend/PortalBackend.Migrations/Seeder/MappingEntityInsertOnlySeeder.cs
https://jira.catena-x.net/browse/CPLP-1042
> fix: cplp-1042 - add data to seeding e.g. iam_identity_providers

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
https://jira.catena-x.net/browse/CPLP-1896
> feature/CPLP-1896 -adding-deactiveEndPoint-appService

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/ViewModels/AppData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
https://jira.catena-x.net/browse/CPLP-1927
> CPLP-1927-api-apps-active-refactor

- src/administration/Administration.Service/BusinessLogic/SdFactoryService.cs
@Phil91 I just found this mismatch - somehow the document type was incorrectly set for the SDFactory IF.
Can you have a small look if we can merge the pr?
> bugfix/Update SdFactoryService.cs

- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
https://jira.catena-x.net/browse/CPLP-1953
Fix provided in this commit for another issue where address id was not storing in company table
> CPLP-1953-fix for-addressid in company  table

- src/administration/Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IDocumentsBusinessLogic.cs
- src/administration/Administration.Service/Controllers/DocumentsController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/DocumentSeedData.cs
- src/portalbackend/PortalBackend.DBAccess/PortalBackend.DBAccess.csproj
- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/DocumentsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/DocumentsControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
In this PR [CPLP-1966](https://jira.catena-x.net/browse/CPLP-1966) is fixed.
> CPLP-1966 document json

- src/administration/Administration.Service/BusinessLogic/DocumentSettings.cs
- src/administration/Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
- src/administration/Administration.Service/Program.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/DocumentsBusinessLogicTests.cs
This PR introduces a new configuration value to enable the document seed endpoint
> CPLP-1966 add custom configuration value for document seed data

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationWithCompanyAddressUserData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
fixes https://jira.catena-x.net/browse/CPLP-1989
(as requested by @jjeroch in PR #66 I renamed the commit and branch which led to closing of PR #66 and creation of this new PR. Content of PR hasn't changed since.)
> CPLP-1989 refactoring SetCompanyWithAddressInternal for untracked entities

- DEPENDENCIES
https://jira.catena-x.net/browse/CPLP-1864
> docs: update dependencies file for v1.0.0-RC1

- src/Portal.Backend.sln
- src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/framework/Framework.DBAccess/EscapeExtensions.cs
- src/framework/Framework.DBAccess/Framework.DBAccess.csproj
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
cleanup of stuff I'd had commented on in PR #39 / #47, if I'd done the review
> CPLP-1855 cleanup adding propper escaping to uses of EF.Functions.ILike

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/AllOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
errorhandling for multiple occourences of leadPictureId removed. What remains implements https://jira.catena-x.net/browse/CPLP-1992
> CPLP-1992 api apps provided by OfferTypeId

- .github/workflows/trivy.yml
increase timeout
skip documents.consortia.json file
> fix: trivy timeout

- src/Portal.Backend.sln
- src/framework/Framework.DBAccess/ContextExtensions.cs
- src/framework/Framework.DBAccess/EscapeExtensions.cs
- src/framework/Framework.DBAccess/Framework.DBAccess.csproj
- src/framework/Framework.Seeding/Framework.Seeding.csproj
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CountryRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICountryRepository.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20230113092045_CPLP-1900-CompanyIdentifiersRename.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20230113092045_CPLP-1900-CompanyIdentifiersRename.cs
- src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
- src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- src/registration/Registration.Service/Model/CompanyDetailData.cs
- src/registration/Registration.Service/Registration.Service.csproj
- tests/framework/Framework.DBAccess.Tests/ContextExtensionsTests.cs
- tests/framework/Framework.DBAccess.Tests/Framework.DBAccess.Tests.csproj
- tests/framework/Framework.Token.Tests/Framework.Token.Tests.csproj
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRespotitoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
implements https://jira.catena-x.net/browse/CPLP-1900 and https://jira.catena-x.net/browse/CPLP-1901
> CPLP-1900, CPLP-1901 GET and POST registration company details unique identifiers

- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferReleaseData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
implements https://jira.catena-x.net/browse/CPLP-2036
> CPLP-2036 remove salesmanagerid from submit offer validation

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/countries.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/country_assigned_identifiers.json
@evegufy can you test this pr please?
@ntruchsess  FYI - the country assigned identifiers updated
> update countries and assigned identifier

- src/framework/Framework.DBAccess/ContextExtensions.cs
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/framework/Framework.DBAccess.Tests/ContextExtensionsTests.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
implements: https://jira.catena-x.net/browse/CPLP-2037
> CPLP-2037 apprelease fix add-remove-usescases

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
fixes https://jira.catena-x.net/browse/CPLP-2037
(previous fix was only a partial fix fixing the insert/delete part of the issue, this fix now fixes the query reading the pre-existing usescases)
> CPLP-2037 apprelease fix add-remove-usescases query

- src/portalbackend/PortalBackend.DBAccess/Models/UploadDocuments.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- src/registration/Registration.Service/Model/CompanyRegistrationData.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
implements https://jira.catena-x.net/browse/CPLP-1904
> CPLP-1904 add company identifier to registration data

- docker/Dockerfile-checklist-worker
> CPLP-1965 checklist worker

- src/portalbackend/PortalBackend.DBAccess/Repositories/IStaticDataRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/StaticDataRepositoryTest.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
follow-up PR to #99
- adding validation of country-codes being returned by bpdm
- adding dbunit-test for the query
> CPLP-1903 add validation of country-codes to bpdm-call

- src/registration/Registration.Service/Controllers/RegistrationController.cs
fixing comment to https://jira.catena-x.net/browse/CPLP-1901
> CPLP-1901 adjust getCompanyDetail return-type metadata

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/mailing/Mailing.Template/TemplateManager.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyAddressIdentifierData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRespotitoryTests.cs
- tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
implements https://jira.catena-x.net/browse/CPLP-1917
> CPLP-1917 add company-identifiers to administration company-details response

- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
implements https://jira.catena-x.net/browse/TEST-492
> TEST-492 add 'at lease one role' validation to create owncompany users

- src/administration/Administration.Service/appsettings.json
- src/framework/Framework.Web/StartupServiceExtensions.cs
- src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
- src/provisioning/Provisioning.Library/IProvisioningManager.cs
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
- src/provisioning/Provisioning.Library/ProvisioningSettings.cs
- src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
- src/provisioning/Provisioning.Service/appsettings.json
- src/registration/Registration.Service/appsettings.json
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
implements https://jira.catena-x.net/browse/CPLP-1891
> CPLP-1891 remove tenant mapper from shared idp creation.

- docker/Dockerfile-maintenance-service
- docker/Dockerfile-portal-migrations
Fixed package references to ErrorHandling.Library for maintenance-service and portal-migrations
Refs: CPLP-1965
> fix(checklist): Fixed package references to errorhandling

- .github/workflows/checklist-worker.yml
- .github/workflows/maintenance-service.yml
- .github/workflows/portal-migrations.yml
- .github/workflows/provisioning-migrations.yml
- docker/Dockerfile-provisioning-migrations
fix the reference for ErrorHandling.Library in the provisioning-migrations dockerfile
Refs: CPLP-1965
> fix(checklist): Fix the provisioning-migrations dockerfile

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/administration/Administration.Service/Models/CompanyWithAddressData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyAddressDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserRoleWithAddress.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
implements https://jira.catena-x.net/browse/CPLP-1917
> CPLP-1917 add unique-identifiers to getCompanyWithAddress admin-registration-endpoint

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationSettings.cs
- src/administration/Administration.Service/appsettings.json
https://jira.catena-x.net/browse/CPLP-2032
> bug/cplp-2032-welcome -email-template-url-missing

- src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
- src/provisioning/Provisioning.Library/IProvisioningManager.cs
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
implements https://jira.catena-x.net/browse/CPLP-2068
> CPLP-2068 add organisatin and username-mapper to own-idp

- .github/workflows/checklist-worker.yml
- src/checklist/Checklist.Worker/Program.cs
- src/checklist/Checklist.Worker/appsettings.json
- src/keycloak/Keycloak.Factory/KeycloakFactory.cs
remove the appsettings config for kubernetes from the checklist worker
correct the logging configuration for checklistService
add additional logging to the checklist worker Program
change keycloak client creation to case insensitive
Refs: CPLP-1617
> fix: remove kubernetes env var from checklist and change keycloak client creation to case insensitive

- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
https://jira.catena-x.net/browse/CPLP-1988
> CPLP-1988-removing-companyShortNameException

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
The checklist entries for endpoint api/administration/registration/applications are ordered by their type
Refs: CPLP-2076
> feat(application): Add order for checklist entries by type

- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/checklist/Checklist.Worker/appsettings.json
- src/externalsystems/Clearinghouse.Library/ClearinghouseService.cs
Refs: [CPLP-1985](https://jira.catena-x.net/browse/CPLP-1985)
> feat(clearinghouse): edit clearinghouse api call

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IConnectorsBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ConnectorsController.cs
- src/administration/Administration.Service/Models/ConnectorInputModel.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ConnectorData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/ConnectorsControllerTests.cs
remove the status from the connector post endpoints add hostId, HostCompanyName, DocumentId and DocumentName to get endpoints
Refs: [CPLP-1961](https://jira.catena-x.net/browse/CPLP-1961)
> feat(connector): refactor connector post and get

- src/notifications/Notifications.Service/Program.cs
enable notifications service to use config from env vars
ref: cplp-1617
needs to be merged right before https://github.com/catenax-ng/tx-portal-cd/pull/11
> enabler: change notifications service to use config from env

- src/marketplace/Apps.Service/Program.cs
- src/marketplace/Services.Service/Program.cs
- src/provisioning/Provisioning.Service/Program.cs
enable provisioning, appmarketplace and services service to use config from env vars
ref: cplp-1617
needs to be merged right before https://github.com/catenax-ng/tx-portal-cd/pull/13
> enabler: change provisioning, appmarketplace and services service to use config from env

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreement_assigned_company_roles.json
> DB-Seeding_update company agreements

- src/administration/Administration.Service/Program.cs
- src/administration/Administration.Service/Properties/launchSettings.json
- src/administration/Administration.Service/appsettings.json
- src/checklist/Checklist.Worker/appsettings.json
- src/externalsystems/Bpdm.Library/BpdmService.cs
- src/framework/Framework.Cors/CorsExtensions.cs
- src/framework/Framework.Web/StartupServiceWebApplicationExtensions.cs
- src/keycloak/Keycloak.ErrorHandling/FlurlErrorHandler.cs
- src/marketplace/Apps.Service/Program.cs
- src/marketplace/Apps.Service/Properties/launchSettings.json
- src/marketplace/Apps.Service/appsettings.json
- src/marketplace/Services.Service/Program.cs
- src/marketplace/Services.Service/Properties/launchSettings.json
- src/marketplace/Services.Service/appsettings.json
- src/notifications/Notifications.Service/Program.cs
- src/notifications/Notifications.Service/Properties/launchSettings.json
- src/notifications/Notifications.Service/appsettings.json
- src/provisioning/Provisioning.Service/Program.cs
- src/provisioning/Provisioning.Service/Properties/launchSettings.json
- src/provisioning/Provisioning.Service/appsettings.json
- src/registration/Registration.Service/Program.cs
- src/registration/Registration.Service/Properties/launchSettings.json
- src/registration/Registration.Service/appsettings.json
enable registration and administration service to use config from env vars
ref: cplp-1617
needs to be merged right before https://github.com/catenax-ng/tx-portal-cd/pull/20
> enabler: change registration and administration service to use config from env

- src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ApplicationRepositoryTests.cs
the endpoint /declineRequest is removed, therefor the logic is implemented in the /decline endpoint
Refs: CPLP-1783
> feat(declineRequest)!: remove /declineRequest endpoint

- docker/Dockerfile-administration-service
- docker/Dockerfile-checklist-worker
- docker/Dockerfile-maintenance-service
- docker/Dockerfile-marketplace-app-service
- docker/Dockerfile-notification-service
- docker/Dockerfile-portal-migrations
- docker/Dockerfile-provisioning-migrations
- docker/Dockerfile-provisioning-service
- docker/Dockerfile-registration-service
- docker/Dockerfile-services-service
https://jira.catena-x.net/browse/CPLP-1906
> fix: add temp fix for cve-2023-0286

- src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/externalsystems/Clearinghouse.Library/BusinessLogic/ClearinghouseBusinessLogic.cs
- src/externalsystems/Clearinghouse.Library/Models/ClearinghouseResponseData.cs
- src/externalsystems/Clearinghouse.Library/Models/ClearinghouseTransferData.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
- tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseBusinessLogicTests.cs
bpn for clearinghouse processing got moved from route to body clearinghouse call now has callback url and exceptProfile included in body
Refs: CPLP-2155
> feat(clearinghouse)!: Adjust clearinghouse calls

- src/checklist/Checklist.Worker/ChecklistProcessor.cs
- src/externalsystems/Bpdm.Library/BpdmService.cs
- src/externalsystems/Bpdm.Library/BpdmServiceCollectionExtension.cs
- src/externalsystems/Bpdm.Library/BusinessLogic/BpdmBusinessLogic.cs
- src/externalsystems/Bpdm.Library/IBpdmService.cs
- src/externalsystems/Clearinghouse.Library/ClearinghouseService.cs
- src/externalsystems/Clearinghouse.Library/ClearinghouseServiceCollectionExtension.cs
- src/externalsystems/Custodian.Library/CustodianService.cs
- src/externalsystems/Custodian.Library/CustodianServiceCollectionExtension.cs
- src/externalsystems/Daps.Library/DapsService.cs
- src/externalsystems/Daps.Library/DapsServiceCollectionExtension.cs
- src/externalsystems/SdFactory.Library/SdFactoryService.cs
- src/externalsystems/SdFactory.Library/SdServiceCollectionExtension.cs
- src/framework/Framework.ErrorHandling.Library/ServiceException.cs
- src/framework/Framework.ErrorHandling.Web/GeneralHttpErrorHandler.cs
- src/framework/Framework.HttpClient/HttpAsyncResponseMessageExtension.cs
- src/framework/Framework.HttpClient/HttpClientExtensions.cs
- src/framework/Framework.Token/Framework.Token.csproj
- src/framework/Framework.Token/TokenService.cs
- tests/checklist/Checklist.Worker.Tests/ChecklistProcessorTests.cs
- tests/externalsystems/Bpdm.Library/BpdmBusinessLogicTests.cs
- tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
- tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseServiceTests.cs
- tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
- tests/externalsystems/SdFactory.Library.Tests/SdFactoryServiceTests.cs
- tests/framework/Framework.Token.Tests/TokenServiceTests.cs
> feature(checklist): unify service-call errorhandling

- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/externalsystems/Clearinghouse.Library/BusinessLogic/ClearinghouseBusinessLogic.cs
- src/externalsystems/Clearinghouse.Library/ClearinghouseSettings.cs
- tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseBusinessLogicTests.cs
> feat(clearinghouse): correct callback url

- src/marketplace/Offers.Library/Service/OfferService.cs
- src/provisioning/Provisioning.Library/Extensions/ClientManager.cs
- src/provisioning/Provisioning.Library/IProvisioningManager.cs
- src/provisioning/Provisioning.Library/ProvisioningManager.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
when creating the client in the autoSetup process the client gets a base address assigned
Refs: CPLP-2079
> feat(autoSetup): add base address to clients

- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/administration/Administration.Service/appsettings.json
- src/mailing/Mailing.Template/EmailTemplates/new_user_account_ownidp.html
- src/mailing/Mailing.Template/Enums/EmailTemplateType.cs
- src/mailing/Mailing.Template/Mailing.Template.csproj
> feat(usermanagement): new email-template for user-creation on own-idp

- src/administration/Administration.Service/Controllers/RegistrationController.cs
External processing endpoints got assigned new permissions
> fix(permissions): add permissions to registration controller

- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- src/framework/Framework.IO/CsvParser.cs
- src/provisioning/Provisioning.Library/Extensions/RoleManager.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
> feat(usermanagement): send email to own-idp users created by upload of usersfile

- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- src/administration/Administration.Service/Controllers/RegistrationController.cs
- src/framework/Framework.IO/CsvParser.cs
- src/provisioning/Provisioning.Library/Extensions/RoleManager.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
to be discussed: we need to decide whether we do normal pull of upstream commit or rather rebase dev on main?
> pull upstream

- src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_roles.json
> feat(user roles): remove bpdm-role 'BPDM Partner Gate' from seeding data

- src/administration/Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
- src/externalsystems/SdFactory.Library/BusinessLogic/SdFactoryBusinessLogic.cs
- src/externalsystems/SdFactory.Library/Models/SelfDescriptionResponseData.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/Controllers/ConnectorsControllerTests.cs
- tests/administration/Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
- tests/externalsystems/SdFactory.Library.Tests/SdFactoryBusinessLogicTests.cs
> fix(sdDocument): self description document is saved correctly

- src/provisioning/Provisioning.Migrations/Migrations/20230223065656_1.0.0.Designer.cs
- src/provisioning/Provisioning.Migrations/Migrations/20230223065656_1.0.0.cs
- src/provisioning/Provisioning.Migrations/Migrations/ProvisioningDbContextModelSnapshot.cs
- src/provisioning/Provisioning.Migrations/Provisioning.Migrations.csproj
replace migrations with one 1.0.0 migration
Refs: CPLP-1909
> feat(provisioning): add initial migration

- src/externalsystems/Clearinghouse.Library/BusinessLogic/ClearinghouseBusinessLogic.cs
- tests/externalsystems/Clearinghouse.Library.Tests/ClearinghouseBusinessLogicTests.cs
override clearinghouse will trigger a start clearinghouse process
> fix: override clearinghouse process fixed

- .github/workflows/administration-service.yml
- .github/workflows/checklist-worker.yml
- .github/workflows/kics.yml
- .github/workflows/maintenance-service.yml
- .github/workflows/marketplace-app-service.yml
- .github/workflows/notification-service.yml
- .github/workflows/portal-migrations.yml
- .github/workflows/provisioning-migrations.yml
- .github/workflows/provisioning-service.yml
- .github/workflows/registration-service.yml
- .github/workflows/services-service.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/trivy-dev.yml
- .github/workflows/trivy-stable.yml
- .github/workflows/unit.tests.yml
> chore: enable dev branch

- src/checklist/Checklist.Worker/ChecklistHandlerService.cs
retrigger of bpdm push and pull added as manual process steps
Refs: CPLP-2266
> fix(checklist): add manual process steps

- src/checklist/Checklist.Executor/ApplicationChecklistProcessTypeExecutor.cs
- src/checklist/Checklist.Executor/ChecklistHandlerService.cs
- src/checklist/Checklist.Executor/IChecklistHandlerService.cs
- src/checklist/Checklist.Worker.Library/IProcessExecutor.cs
- src/checklist/Checklist.Worker.Library/IProcessTypeExecutor.cs
- src/checklist/Checklist.Worker.Library/ProcessExecutionService.cs
- src/checklist/Checklist.Worker.Library/ProcessExecutor.cs
- src/framework/Framework.Async/AsyncGroupByExtensions.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IProcessStepRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ProcessStepRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
- tests/checklist/Checklist.Worker.Library.Tests/ProcessExecutionServiceTests.cs
- tests/checklist/Checklist.Worker.Library.Tests/ProcessExecutorTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ProcessStepRepositoryTests.cs
> fix(checklist): ensure propper dispose of async enumerators

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/AppDeleteData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
added new endpoint to delete an app 
Refs: CPLP-2103
> feat(appReleaseProcess): delete app

- src/portalbackend/PortalBackend.DBAccess/Models/AppWithSubscriptionStatus.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
Modified endpoint /api/apps/subscribed/subscription-status for additional attribute in response
Refs: CPLP-2252
> feat(app): subscribe app

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
Enhanced end point  /api/apps/{appId}/appImages/{documentId}  to support additional document type of pdf
Refs: CPLP-2268
> feat(app): get appdocument(pdf) refactoring

- src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppChangeBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppChangeController.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/marketplace/Apps.Service/Extensions/AppExtensions.cs
- src/marketplace/Apps.Service/Program.cs
- src/marketplace/Apps.Service/ViewModels/AppUserRole.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
- src/provisioning/Provisioning.Library/Extensions/RoleManager.cs
- src/provisioning/Provisioning.Library/IProvisioningManager.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppChangeControllerTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
- tests/provisioning/Provisioning.Library.Tests/RoleManagerTests.cs
introduce new endpoint /apps/appchange
move the endpoint to add roles to an active app from apprelease to appchange
BREAKING CHANGE: endpoint moved
Refs: CPLP-1565
> feat(app)!: move ep to add roles to active app

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyRoleConsentData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanyRoleConsentDatas.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
new endpoint to get CompanyRoles and ConsentAgreement Details
Ref: CPLP-1528
> feature/cplp-1528-get-companyRoleConsentDetails 

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
upload AppleadImage Document , update existing
AppLeadImage Document Status to InActive and remove it.
Ref : CPLP-1555
> feat : newendpoint-post offerAssignedAppLeadImageDocument

- src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
- src/administration/Administration.Service/Controllers/UserController.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
affected endpoints:
POST: api/administration/user/owncompany/identityprovider/{identityProviderId}/usersfile
POST: api/administration/user/owncompany/identityprovider/{identityProviderId}/users
POST: api/administration/user/owncompany/usersfile
Refs: CPLP-2075
> feature(usercreation): add check for minimum one role

- src/checklist/Checklist.Library/ChecklistCreationService.cs
- src/checklist/Checklist.Library/ChecklistService.cs
- src/checklist/Checklist.Library/IChecklistCreationService.cs
- src/checklist/Checklist.Worker.Library/ProcessExecutor.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IProcessStepRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ProcessStepRepository.cs
- tests/checklist/Checklist.Library.Tests/ChecklistCreationServiceTests.cs
- tests/checklist/Checklist.Library.Tests/ChecklistServiceTests.cs
- tests/checklist/Checklist.Worker.Library.Tests/ProcessExecutorTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ProcessStepRepositoryTests.cs
> fix(registration): fix process-creation on application submission

- src/checklist/Checklist.Library/ChecklistCreationService.cs
- src/checklist/Checklist.Library/IChecklistCreationService.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/checklist/Checklist.Library.Tests/ChecklistCreationServiceTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
> fix(registration): fix error allready tracked entity on application submit

- docker/Dockerfile-administration-service
- docker/Dockerfile-checklist-worker
- docker/Dockerfile-maintenance-service
- docker/Dockerfile-marketplace-app-service
- docker/Dockerfile-notification-service
- docker/Dockerfile-portal-migrations
- docker/Dockerfile-provisioning-migrations
- docker/Dockerfile-provisioning-service
- docker/Dockerfile-registration-service
- docker/Dockerfile-services-service
- add temp fix for CVE-2022-1304
- remove obsolete temp fix for CVE-2023-0286
> fix(cve-2022-1304): add package upgrade as temp fix

- src/mailing/Mailing.Template/EmailTemplates/nextsteps.html
Email Template "Next Steps" html updated.
- "quick links" deleted since they are not necessary/needed for this email template
- padding updated
> change (emailTemplate): update content next steps

- src/mailing/Mailing.Template/EmailTemplates/nextsteps.html
https://github.com/catenax-ng/tx-portal-backend/pull/226 was wrongly merged into main.
Merge main into dev to get the change to dev env.
> Merge (main in dev): update email template

- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- src/marketplace/Services.Service/Program.cs
- src/marketplace/Services.Service/ViewModels/ServiceData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ServiceDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ServiceTypeData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IStaticDataRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/StaticDataRepositoryTest.cs
added new endpoint to get service type data
Refs: CPLP-2347, CPLP-2293
> feat(serviceRelease): get service type

- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
added new endpoint to fetch agreement and consent data for an offer of service type
Refs: CPLP-2350
> feat(serviceRelease): get offer agreement consent data

- .github/workflows/trivy-dev.yml
- .github/workflows/trivy.yml
- .tractusx
- https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
ref.: CPLP-2334
- chore(trivy) set to fixed container registry
> chore(trg and trivy): add repo metafile and fixed container registry

- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
> fix(service): change permission for serviceStatus

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
> fix: resolving the conflictException

- src/administration/Administration.Service/BusinessLogic/DocumentSettings.cs
- src/administration/Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/IDocumentsBusinessLogic.cs
- src/administration/Administration.Service/Controllers/DocumentsController.cs
- src/administration/Administration.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/BusinessLogic/RegistrationSettings.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- src/registration/Registration.Service/appsettings.json
- tests/administration/Administration.Service.Tests/BusinessLogic/DocumentsBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/DocumentsControllerTests.cs
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/registration/Registration.Service.Tests/Controller/RegistrationControllerTest.cs
added new endpoint to get administration frame document 
Refs: CPLP-2342
> feat(administration/document): get frame document

- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
added new endpoint to get registration document of CX_FRAME_CONTRACT documenttypeid
Refs: CPLP-2341
> feat(registration): get registration document

- src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
- src/administration/Administration.Service/Controllers/CompanyDataController.cs
- src/administration/Administration.Service/Models/CompanyRoleConsentDetails.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
- tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
new endpoint to create CompnayRole and Consent records 
Ref : CPLP-1529
> feat: create company role and consent data

- src/framework/Framework.DBAccess/ContextExtensions.cs
- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/marketplace/Offers.Library/Models/ConsentStatusData.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferAgreementConsent.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/AgreementRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConsentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IAgreementRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IConsentRepository.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConsentRepositoryTests.cs
add endpoint set the consent to agreements for a specific service remove service serviceAgreementConsent endpoints from service controller
Refs: CPLP-2376
> feat(service): add endpoint for service consent

- src/marketplace/Offers.Library/Service/OfferService.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Updated the business logic to remove the validation for attribute user role which is mandatory only for App not for service submit flow
Ref:-CPLP-2423
> fix(service): Put Submit Service

- src/administration/Administration.Service/BusinessLogic/DocumentsBusinessLogic.cs
- src/framework/Framework.DBAccess/ContextExtensions.cs
- src/marketplace/Offers.Library/Models/ConsentStatusData.cs
- src/marketplace/Offers.Library/Models/OfferingData.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConsentRepository.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20230323103650_CPLP-2363-AddConsentIndex.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20230323103650_CPLP-2363-AddConsentIndex.cs
- src/portalbackend/PortalBackend.PortalEntities/Entities/Consent.cs
- src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
- tests/framework/Framework.DBAccess.Tests/ContextExtensionsTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConsentRepositoryTests.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Add possibility to set the provider uri when creating a service
Refs: CPLP-2363
> feat(service): add provider uri to post

- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
change permission role for Get Service Details
api/services/servicerelease/inReview/serviceId
Ref:-CPLP-2377
> bug(serviceRelease): Get Service Details

- .github/workflows/sonarcloud.yml
- .github/workflows/trivy-dev.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yaml
- docker/Dockerfile-administration-service
- docker/Dockerfile-checklist-worker
- docker/Dockerfile-maintenance-service
- docker/Dockerfile-marketplace-app-service
- docker/Dockerfile-notification-service
- docker/Dockerfile-portal-migrations
- docker/Dockerfile-provisioning-migrations
- docker/Dockerfile-provisioning-service
- docker/Dockerfile-registration-service
- docker/Dockerfile-services-service
- fix(trivy): upgrade upload-sarif action
- chore(checkout): upgrade action
- fix(cve-2023-0464): add temp fix
ref: CPLP-2456
> fix(security-findings): upgrade actions and add temp fix for CVE-2023-0464

- .github/workflows/administration-service.yml
- .github/workflows/checklist-worker.yml
- .github/workflows/maintenance-service.yml
- .github/workflows/marketplace-app-service.yml
- .github/workflows/notification-service.yml
- .github/workflows/portal-migrations.yml
- .github/workflows/provisioning-migrations.yml
- .github/workflows/provisioning-service.yml
- .github/workflows/registration-service.yml
- .github/workflows/release.yml
- .github/workflows/services-service.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/veracode.yaml
- docker and workflow-application-token actions in build workflows
- actions in sonarcloud and veracode workflows
ref: CPLP-2457
> chore(workflows): update actions

- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- src/marketplace/Services.Service/ServiceSettings.cs
- src/marketplace/Services.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/Models/InReviewServiceData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
New Endpoint to Get all services in status "in Review" & "ACTIVE" 
ref:- CPLP-2417
> feat(servicerelease):get offer(services) in_review and active state

- .github/workflows/release-candidate.yml
ref: ref: CPLP-2330
related to https://github.com/catenax-ng/tx-portal-cd/pull/57
> build(env): add build workflow for v1.3.0 release candidate phase

- .github/workflows/release.yml
> chore(workflows): direct dispatch to renamed workflow file

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connectors.test.json
updating DocumentStatus to InActive when it
hit the Delete Connector Endpoint
Ref: CPLP-2197
> feat(connector): updating DocumentStatus

- src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/registration/Registration.Service/Controllers/RegistrationController.cs
- tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Added an check for DocumentTypeIds
Ref: CPLP-2194
> feat: added an check for documentTypeIds

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/ViewModels/InReviewAppDetails.cs
- src/portalbackend/PortalBackend.DBAccess/Models/InReviewOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
added privacypolicies attribute in response for endpoint api/apps/appreleaseprocess/inReview/appId
ref:- CPLP-2370
> feat(appreleaseprocess): get inReviewapp 

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Offers.Library/Service/IOfferService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- src/marketplace/Services.Service/ServiceSettings.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/DocumentRepositoryTests.cs
feat: new endpoint for serviceRelease to deleteDocument
Added Config Variable for deleteDocumentTypeIds 
PR - https://github.com/catenax-ng/tx-portal-cd/pull/63
Ref: CPLP-2493
> feat: new endpoint for serviceRelease to deleteDocument

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/ViewModels/AppDetailResponse.cs
- src/marketplace/Apps.Service/ViewModels/InReviewAppDetails.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/ViewModels/ServiceData.cs
- src/marketplace/Services.Service/ViewModels/ServiceDetailResponse.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ActiveAppData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/InReviewOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferDetailsData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ServiceDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ServiceOverviewData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
added license type attribute for get endpoint 
ref:- CPLP-2490
> feat(apps&services&appreleaseprocess)  get endpoint of apps and services

- src/Portal.Backend.sln
- src/framework/Framework.Async/AwaitAllIAsyncEnumerableExtension.cs
- src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
- src/notifications/Notifications.Library/INotificationService.cs
- src/notifications/Notifications.Library/NotificationService.cs
- src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
- tests/framework/Framework.Async.Tests/Framework.Async.Tests.csproj
- tests/framework/Framework.Async.Tests/IAsyncEnumerableExtensionTests.cs
- tests/framework/Framework.Async.Tests/Usings.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
- tests/notifications/Notifications.Library.Tests/NotificationServiceTests.cs
- tests/registration/ApplicationActivation.Library.Tests/ApplicationActivationTests.cs
- tests/shared/Tests.Shared/Extensions/FakeIAsyncEnumerableExtensions.cs
the notifications will only be created once per request for each user and type
Refs: CPLP-2526
> fix(notification): create only one notification per user

- CHANGELOG.md
- src/Directory.Build.props
- src/Portal.Backend.sln
- src/framework/Framework.Async/AwaitAllIAsyncEnumerableExtension.cs
- src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
- src/marketplace/Offers.Library/Models/OfferingData.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/ViewModels/ServiceUpdateData.cs
- src/notifications/Notifications.Library/INotificationService.cs
- src/notifications/Notifications.Library/NotificationService.cs
- src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
- tests/framework/Framework.Async.Tests/Framework.Async.Tests.csproj
- tests/framework/Framework.Async.Tests/IAsyncEnumerableExtensionTests.cs
- tests/framework/Framework.Async.Tests/Usings.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/notifications/Notifications.Library.Tests/NotificationServiceTests.cs
- tests/registration/ApplicationActivation.Library.Tests/ApplicationActivationTests.cs
- tests/shared/Tests.Shared/Extensions/FakeIAsyncEnumerableExtensions.cs
> release(1.3.0-RC3): merge release into main

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> fix(connector): set utcNow instead of now

- src/marketplace/Offers.Library/Service/OfferSetupService.cs
add offerId and offerName to notification content
Refs: CPLP-2545
> fix: extend notification content for TECHNICAL_USER_CREATION

- src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyUserAssignedBusinessPartner.cs
- src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
- tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceCreateUsersTests.cs
> feat(administration): add assigned businessPartnerNumber on new User creation

- CHANGELOG.md
- src/Directory.Build.props
- src/marketplace/Services.Service/appsettings.json
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
> release(1.3.0-RC4): merge main into dev

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Offers.Library/Service/IOfferSetupService.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Offers.Library/Service/OfferSetupService.cs
- src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/notifications/Notifications.Library/INotificationService.cs
- src/notifications/Notifications.Library/NotificationService.cs
- src/portalbackend/PortalBackend.DBAccess/Models/NotificationDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20230421082532_CPLP-2569-NotificationDoneNullable.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20230421082532_CPLP-2569-NotificationDoneNullable.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
- src/portalbackend/PortalBackend.Migrations/Seeder/Data/notification_type_assigned_topic.json
- src/portalbackend/PortalBackend.PortalEntities/Entities/Notification.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSetupServiceTests.cs
- tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/notifications/Notifications.Library.Tests/NotificationServiceTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
- tests/registration/ApplicationActivation.Library.Tests/ApplicationActivationTests.cs
enhance done state for notifications
set notifications for App and Service Subscription Requests to done in the autosetup process
Refs: CPLP-2569
> feat(notification): enhance done state

- src/portalbackend/PortalBackend.DBAccess/Models/CompanySubscriptionStatusData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
refactoring of end point api/services/provided/subscription-status  to add additional attribute i.e Customer Country, Email and Company BpnNumber
ref:- CPLP-439
> feat(services):-get provided subscription status

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
feat(appRelease): adding Obsolete filter for updateapp endpoint
Ref: CPLP-2437
> feat(appRelease): adding Obsolete filter for updateapp endpoint

- src/marketplace/Offers.Library/Service/OfferService.cs
feat: adding offerName for Notification content
Ref: CPLP-2419, CPLP-2565
> feat: adding offerName for Notification content

- src/provisioning/Provisioning.Library/Service/ServiceAccountCreation.cs
- tests/provisioning/Provisioning.Library.Tests/ServiceAccountCreationTests.cs
> fix(serviceAccount): fix naming of service account

- src/notifications/Notifications.Service/Controllers/NotificationController.cs
- tests/notifications/Notifications.Service.Tests/Controllers/NotificationControllerTest.cs
remove POST: /api/notification
fix swagger docu
Refs: CPLP-2585, CPLP-1982
> feat(notification)!: remove post endpoint

- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationSettings.cs
- src/administration/Administration.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/Models/EmailData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/WelcomeEmailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
- src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
- tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
- tests/registration/ApplicationActivation.Library.Tests/ApplicationActivationTests.cs
corresponding CD PR https://github.com/catenax-ng/tx-portal-cd/pull/76
added bpn for  EmailRegistrationWelcomeTemplate during registration activation
Refs: CPLP-1801
> feature(Registration): added bpn for  EmailRegistrationWelcomeTemplate 

- src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
- src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
- src/administration/Administration.Service/Controllers/ConnectorsController.cs
- src/framework/Framework.DBAccess/EscapeExtensions.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
- tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/PortalBackend.DBAccess.Tests.csproj
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/connectors.test.json
retrieve connector end point data for specified input bpn as well null value
api/administration/connectors/discovery
ref:-CPLP-2524
> feature(connector):-Post discovery to fetch connector end point

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/ViewModels/InReviewAppDetails.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/ViewModels/ServiceData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/InReviewOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ServiceDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/offers.test.json
feat: refactoring inReview endpoints for Apps and Service
Ref: CPLP-2504
> feat: refactoring inReview endpoints for Apps and Service

- src/externalsystems/Custodian.Library/CustodianService.cs
- src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
- src/framework/Framework.HttpClient/HttpAsyncResponseMessageExtension.cs
- tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
> feat(custodian): add extended error logging

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
filter offer by Id for the respective subscription details.
api/apps/provided/subscription-status
api/servicess/provided/subscription-status
ref:- CPLP-1537
> feature(app&service):- get provided subscription status

- src/Portal.Backend.sln
- src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
- src/administration/Administration.Service/Program.cs
- src/administration/Administration.Service/appsettings.json
- src/framework/Framework.Web/HealthCheckExtensions.cs
- src/framework/Framework.Web/HealthCheckSettings.cs
- src/framework/Framework.Web/JwtBearerConfigurationHealthCheck.cs
- src/framework/Framework.Web/StartupServiceExtensions.cs
- src/framework/Framework.Web/StartupServiceWebApplicationExtensions.cs
- src/marketplace/Apps.Service/appsettings.json
- src/marketplace/Services.Service/appsettings.json
- src/notifications/Notifications.Service/appsettings.json
- src/portalbackend/PortalBackend.DBAccess/PortalBackend.DBAccess.csproj
- src/provisioning/Provisioning.DBAccess/Provisioning.DBAccess.csproj
- src/provisioning/Provisioning.DBAccess/ProvisioningDBAccessStartupServiceExtensions.cs
- src/provisioning/Provisioning.Service/appsettings.json
- src/registration/Registration.Service/appsettings.json
- tests/framework/Framework.Web.Tests/HealthCheckExtensionsTests.cs
- tests/framework/Framework.Web.Tests/JwtBearerConfigurationHealthCheckTests.cs
- tests/framework/Framework.Web.Tests/Usings.cs
corresponding CD-PR: https://github.com/catenax-ng/tx-portal-cd/pull/77
* add healthchecks to ensure pod is finished initializing config before facing traffic
Refs: CPLP-2567
> bugfix(authentication): fix config errors on initialization

- src/marketplace/Services.Service/BusinessLogic/IServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
- src/marketplace/Services.Service/ViewModels/ServiceReleaseStatusIdFilter.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceReleaseControllerTest.cs
added filter for inreview and active status for endpoint api/services/servicerelease/inReview
ref:-CPLP-2417
> feat(servicerelease): get inreview and active service

- src/marketplace/Apps.Service/Controllers/AppChangeController.cs
- src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
swagger documentation endpoint summary changes
api/apps/AppReleaseProcess/updateappdoc/{appId}/documentType/{documentTypeId}/documents
api/apps/AppChange/{appId}/role/activeapp
api/apps/appagreementdata/{appId}
ref:- CPLP-2604
> bug(apps):- swagger documentation clean up

- src/notifications/Notifications.Service/BusinessLogic/NotificationBusinessLogic.cs
- src/portalbackend/PortalBackend.DBAccess/Models/NotificationCountDetails.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
- tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
/api/notification/count got enhanced with the done state for the actionRequired notification count
Refs: CPLP-2601
> feat(notification): Enhance notification count ep

- CHANGELOG.md
> release: update changelog for v1.3.0

- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/ViewModels/ServiceData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ServiceDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
added technicaluserdetail in response for inReview endpoint 
api/services/servicerelease/inReview/{serviceId}
ref:-CPLP-2612
> feat(serviceRelease)-get inReview by ServiceId

- src/marketplace/Offers.Library/Models/OfferProviderResponse.cs
- src/marketplace/Offers.Library/Service/OfferService.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
- src/marketplace/Services.Service/ViewModels/ServiceProviderResponse.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferProviderData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/ServiceDetailData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
get techniicaluserdetail for servicestatus endpoint in servicerelease api
api/services/servicerelease/{serviceId}/serviceStatus
ref:-CPLP-2613
> feat(servicerelease)-get servicestatus by serviceid

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/ViewModels/InReviewAppDetails.cs
- src/portalbackend/PortalBackend.DBAccess/Models/InReviewOfferData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppReleaseProcessControllerTest.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
added technicaluserprofile to response of ednpoint
api/apps/appreleaseprocess/inReview/{appId
ref:-CPLP-2614
> feature(appreleaseprocess): get inReview appId 

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Offers.Library/Models/BusinessAppData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
feat(appService): added offerId to app-business-endPoint
Ref: CPLP-2655
> feat(appService): added offerId to app-business-endPoint

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/ViewModels/AppProviderResponse.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
add technicaluserdetail in response of appreleaseprocess appstatus endpoint
api/apps/appreleaseprocess/{appId}/appStatus
Refs: CPLP-2615
> feature(appreleaseprocess):-get appid appstatus

- .github/workflows/sonarcloud.yml
follow up to https://github.com/catenax-ng/tx-portal-backend/pull/380
> fix(sonarcloud): run still on push

- src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/ViewModels/AppWithSubscriptionStatus.cs
- src/portalbackend/PortalBackend.DBAccess/Models/AppWithSubscriptionStatus.cs
- src/portalbackend/PortalBackend.DBAccess/PortalRepositories.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
add leadimage in response of endpoint
api/apps/subscribed/subscription-status
ref:- CPLP-2635
> feature(apps)- get app-subscribed-subscription-status

- src/portalbackend/PortalBackend.Migrations/Migrations/20230512055259_CPLP-2359-FixConnectorAudit.Designer.cs
- src/portalbackend/PortalBackend.Migrations/Migrations/20230512055259_CPLP-2359-FixConnectorAudit.cs
> fix: correct audit connector table

- src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
- src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
- src/marketplace/Apps.Service/Controllers/AppsController.cs
- src/marketplace/Apps.Service/ViewModels/OfferCompanySubscriptionStatusResponse.cs
- src/marketplace/Offers.Library/Models/OfferCompanySubscriptionStatusResponse.cs
- src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
- src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
- src/marketplace/Services.Service/Controllers/ServicesController.cs
- src/portalbackend/PortalBackend.DBAccess/Models/CompanySubscriptionStatusData.cs
- src/portalbackend/PortalBackend.DBAccess/Models/OfferCompanySubscriptionStatusData.cs
- src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
- tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
- tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
- tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
- tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
add leadImage in response of apps provided subscription-status enpoint
apps/provided/subscription-status
ref:-CPLP-2646
> feature(apps)- get provided subscription-status

- .github/workflows/iam-seeding.yml
- .github/workflows/release_iam-seeding.yml
- .github/workflows/trivy-dev.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yaml
- docker/notice-iam-seeding.md
- add build and release workflows
- add security scans
GH actions need to enabled.
https://github.com/eclipse-tractusx/portal-backend/pull/184
Please delete options that are not relevant.
> feat(iam-seeding): enable workflows

- CHANGELOG.md
Add changes for v1.7.0-alpha to changelog
to have the latest changes available in the changelog
N/A
> release: update changelog for v1.7.0-alpha

- CHANGELOG.md
- src/Directory.Build.props
* update changelog for v1.7.0-RC1
* bump version for v1.7.0-RC1
To have the latest changelog and version for the release
N/A
> release: update changelog for v1.7.0-RC1

- CHANGELOG.md
- src/Directory.Build.props
* update changelog for v1.8.0-RC4
* bump version for v1.8.0-RC4
To have the latest changes for the release within the changelog
[#151](https://github.com/eclipse-tractusx/portal-cd/issues/151)
> build: update changelog for v1.8.0-RC4
